name: tests
on:
  push:
    branches: ['*', '*/*', master]

jobs:
  run_pytest:
    name: Run pytest for Evalme
    runs-on: ubuntu-latest
    env:
      LOG_DIR: pytest_logs
      collect_analytics: false

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4.2.0
        with:
          python-version: '3.7'

      - uses: actions/cache@v3
        name: Configure pip cache
        id: pip-cache
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}-${{ hashFiles('requirements-test.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          sudo apt-get clean
          sudo apt-get update
          sudo apt-get install virtualenv libsasl2-dev python-dev libldap2-dev libssl-dev
          pip install -U pip==20.2
          pip install -r requirements.txt -r requirements-test.txt 

      - name: Run functional tests
        run: |
          cd evalme/
          pytest --junitxml report.xml --cov=. -m "not integration_tests"

      - name: "Upload coverage to Codecov"
        uses: codecov/codecov-action@v3.1.0
        with:
          name: codecov
          files: ./evalme/report.xml
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
