name: tests
on:
  push:
    branches:
      - master
      - 'release/**'
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    branches:
      - master
      - 'release/**'

jobs:
  run_pytest:
    name: Run pytest for Evalme
    runs-on: ubuntu-latest
    env:
      LOG_DIR: pytest_logs
      collect_analytics: false

    steps:
      - uses: actions/checkout@v4

      - name: "Install dependencies"
        run: |
          sudo apt-get update
          sudo apt-get install libldap2-dev libsasl2-dev libssl-dev libxml2-dev libxslt-dev libgeos-c1v5

      - name: "Set up Python"
        uses: actions/setup-python@v5.3.0
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: "Install main and test dependencies"
        run: |
          pip install -r requirements.txt -r requirements-test.txt 

      - name: "Run functional tests"
        run: |
          cd evalme/
          pytest --junitxml report.xml --cov=. -m "not integration_tests"

      - name: "Upload coverage to Codecov"
        uses: codecov/codecov-action@v5.3.1
        with:
          name: codecov
          files: ./evalme/report.xml
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true

  dependabot-auto-merge:
    name: "Auto Merge dependabot PR"
    if: |
      always() &&
      needs.run_pytest.result == 'success' &&
      github.event_name == 'pull_request' &&
      github.event.pull_request.user.login == 'dependabot[bot]' &&
      ( startsWith(github.head_ref, 'dependabot/npm_and_yarn/') || startsWith(github.head_ref, 'dependabot/pip/') )
    runs-on: ubuntu-latest
    needs:
      - run_pytest
    steps:
      - name: Enable auto-merge for Dependabot PRs
        run: gh pr merge --admin --squash "${PR_URL}"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GIT_PAT }}
